name: "Spack Binary Release Action"
description: "Build and release a package.py in a source repository with spack."
inputs:
  spack_yaml:
    description: A spack yaml to install and add to the build cache
    required: true
  repos:
    description: comma separated list of additional repos to clone and add
    required: false
  branch:
    description: Spack branch to clone
    required: false
    default: develop
  release:
    description: A spack release to use (if defined, overrides branch)
    required: false
    default: ""
  token:
    description: A GitHub token required if releasing artifacts to the same repository
    required: true
  flags:
    description: Extra flags (compiler, target, variants, etc) to add to the install command
    required: false
  tag:
    description: Tag to use for package (defaults to latest)
    required: false
  deploy:
    description: Deploy (release) package to GitHub repository (token is required)
    required: true
    default: false

outputs:
  package_name:
    description: "package name uploaded to"
    value: ${{ steps.release.outputs.package_name }}
  package_tagged_name:
    description: "package name with custom tag uploaded to"
    value: ${{ steps.release.outputs.package_name }}
  package_tag:
    description: "package tag (along with latest)"
    value: ${{ steps.release.outputs.package_tag }}
  package_content_type:
    description: "the package content type"
    value: ${{ steps.release.outputs.content_type }}
  spec_jsons:
    description: "comma separately list of json files in the cache to describe the entry."
    value: ${{ steps.build.outputs.spec_jsons }}
  build_cache:
    description: "Build cache path (dated YY.MM)"
    value: ${{ steps.build.outputs.build_cache }}
  build_cache_prefix:
    description: Prefix of spack build cache (directory above build_cache)
    value: ${{ steps.build.outputs.build_cache_prefix }}
  spec:
    description: "Spec used for build"
    value: ${{ steps.build.outputs.spec }}

runs:
  using: "composite"
  steps:
    - name: Set Root Directory
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: ${{ github.action_path }}/scripts/set_root.sh
      shell: bash

    - name: Install Spack and Dependencies
      env:
        INPUT_SPACK_BRANCH: ${{ inputs.branch }}
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_REPOS: ${{ inputs.repos }}
        INPUT_SPACK_ROOT: /opt/spack
      run: ${{ env.ACTION_ROOT }}/install/scripts/install.sh
      shell: bash

    - name: Build Packages
      id: build
      env:
        INPUT_SPACK_YAML: ${{ inputs.spack_yaml }}
        INPUT_FLAGS: ${{ inputs.flags }}
        ACTION_ROOT: ${{ github.action_path }}
      run: ${{ github.action_path }}/scripts/build.sh
      shell: bash

    - name: Package Release
      id: release
      env:
        INPUT_PACKAGE_NAME: ${{ inputs.package }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_ACTOR: ${{ github.actor }}
        INPUT_TAG: ${{ inputs.tag }}
        BUILD_CACHE_PREFIX: ${{ env.build_cache_prefix }}
        BUILD_CACHE: ${{ env.build_cache }}
        SPACK_ROOT: /opt/spack
        DEPLOY: ${{ inputs.deploy }}
      run: ${{ github.action_path }}/scripts/release.sh
      shell: bash
