name: "Spack Install Action"
description: "Install your branch or release of spack at your root of choice."
inputs:
  repos:
    description: comma separated list of additional repos to clone and add
    required: false
  spack_root:
    description: root to install spack to (defaults to /opt/spack)
    required: false
    default: /opt/spack
  branch:
    description: The branch of spack to use (defaults to develop)
    required: false
    default: develop
  release:
    description: A spack release to use (if defined, overrides branch)
    required: false
    default: ""
  full_clone:
    description: Instead of cloning with --depth 1, clone the entire git history (branch only)
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Spack and Dependencies
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_REPOS: ${{ inputs.repos }}
        INPUT_FULL_CLONE: ${{ inputs.full_clone }}
        INPUT_SPACK_ROOT: ${{ inputs.spack_root }}
      run: ${{ github.action_path }}/scripts/install.sh
      shell: bash
